dbt_sales_data_processing:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "aj60515.us-east-2.aws"
      user: "PHILMAYELE"
      password: "Costa1234"
      role: "ACCOUNTADMIN"
      database: "E_COMMERCE_DB"
      warehouse: "COMPUTE_WH"
      schema: "E_COMMERCE_SCHEMA"
      threads: 4
      client_session_keep_alive: false